[project]
name = "stackone-ai"
version = "0.0.2"
description = "tools for stackone"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "langchain-core>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true
