name: Lint & Type Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        include:
          - python-version: "3.9"
            sync-extras: "--all-extras --no-extra mcp"
          - python-version: "3.10"
            sync-extras: "--all-extras"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync ${{ matrix.sync-extras }}

      - name: Run Ruff
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1
        with:
          args: check .

      - name: Run Mypy
        run: |
          if [[ "${{ matrix.python-version }}" == "3.9" ]]; then
            uv run mypy stackone_ai --exclude stackone_ai/server.py
          else
            uv run mypy stackone_ai
          fi
